version: '3.8'
# https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-containers-ad-auth-adutil-tutorial?view=sql-server-ver16#create-the-config-files-to-be-used-by-the-sql-server-container
# https://stackoverflow.com/questions/65601077/unable-to-run-sql-server-2019-docker-with-volumes-and-get-error-setup-failed-co

# image names must be lowercase
services:
  mssql_server:
    container_name: mssql_server
    image: dev_sqlserver:2019
    restart: always
    user: mssql
    env_file: .env
    environment:
      - PATH=${SQL_PATH}:${PATH}
    volumes:
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/backup:/var/opt/mssql/backup
      - ./mssql/secrets:/var/opt/mssql/secrets
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Secret1234 -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 10
    ports:
      - 1433:1433
    networks:
      - sql_network

networks:
  sql_network:
    external: true
